DROP TABLE IF EXISTS CIP;

CREATE TABLE CIP (
    Code VARCHAR(10),
    Description VARCHAR(255),
    PRIMARY KEY (Code)
);

INSERT INTO CIP VALUES
('01','Agriculture, Agriculture Operations, and Related Sciences'),
('03','Natural Resources and Conservation'),
('04','Architecture and Related Services'),
('05','Area, Ethnic, Cultural, and Gender Studies'),
('09','Communication, Journalism, and Related Programs'),
('10','Communications Technologies/Technicians and Support Services'),
('11','Computer and Information Sciences and Support Services'),
('12','Personal and Culinary Services'),
('13','Education'),
('14','Engineering'),
('15','Engineering Technologies/Technicians'),
('16','Foreign Languages, Literatures, and Linguistics'),
('19','Family and Consumer Sciences/Human Sciences'),
('22','Legal Professions and Studies'),
('23','English Language and Literature/Letters'),
('24','Liberal Arts and Sciences, General Studies and Humanities'),
('25','Library Science'),
('26','Biological and Biomedical Sciences'),
('27','Mathematics and Statistics'),
('28','Reserve Officer Training Corps (JROTC, ROTC)'),
('29','Military Technologies'),
('30','Multi/Interdisciplinary Studies'),
('31','Parks, Recreation, Leisure, and Fitness Studies'),
('32','Basic Skills'),
('33','Citizenship Activities'),
('34','Health-Related Knowledge and Skills'),
('35','Interpersonal and Social Skills'),
('36','Leisure and Recreational Activities'),
('37','Personal Awareness and Self-Improvement'),
('38','Philosophy and Religious Studies'),
('39','Theology and Religious Vocations'),
('40','Physical Sciences'),
('41','Science Technologies/Technicians'),
('42','Psychology'),
('43','Security and Protective Services'),
('44','Public Administration and Social Service Professions'),
('45','Social Sciences'),
('46','Construction Trades'),
('47','Mechanic and Repair Technologies/Technicians'),
('48','Precision Production'),
('49','Transportation and Materials Moving'),
('50','Visual and Performing Arts'),
('51','Health Professions and Related Clinical Sciences'),
('52','Business, Management, Marketing, and Related Support Services'),
('53','High School/Secondary Diplomas and Certificates'),
('54','History'),
('60','Residency Programs');
